#############################################################################
# Makefile for building: Cargo\ App
# Generated by qmake (3.1) (Qt 6.3.1)
# Project:  container.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile container.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=12 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=12 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/share/qt/mkspecs/macx-clang -F/usr/local/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Cargo\ App1.0.0
DISTDIR = /Users/osidon/Docs/Container/container/.tmp/Cargo\ App1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/lib
LIBS          = $(SUBLIBS) -F/usr/local/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtConcurrent -framework QtNetwork -framework QtXml -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		src/allocated_packages.cpp \
		src/backup.cpp \
		src/box.cpp \
		src/box_view.cpp \
		src/containers.cpp \
		src/cylinder.cpp \
		src/cylinder_view.cpp \
		src/mainclient.cpp \
		src/network_client.cpp \
		src/package.cpp \
		src/post_xml.cpp \
		src/unallocated_list.cpp \
		src/unallocated_view.cpp moc_box_view.cpp \
		moc_containers.cpp \
		moc_cylinder_view.cpp \
		moc_mainclient.cpp \
		moc_post_xml.cpp \
		moc_unallocated_view.cpp
OBJECTS       = main.o \
		allocated_packages.o \
		backup.o \
		box.o \
		box_view.o \
		containers.o \
		cylinder.o \
		cylinder_view.o \
		mainclient.o \
		network_client.o \
		package.o \
		post_xml.o \
		unallocated_list.o \
		unallocated_view.o \
		moc_box_view.o \
		moc_containers.o \
		moc_cylinder_view.o \
		moc_mainclient.o \
		moc_post_xml.o \
		moc_unallocated_view.o
DIST          = /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllint_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		container.pro headers/allocated_packages.h \
		headers/backup.h \
		headers/box.h \
		headers/box_view.h \
		headers/containers.h \
		headers/cylinder.h \
		headers/cylinder_view.h \
		headers/mainclient.h \
		headers/network_\ client.h \
		headers/package.h \
		headers/post_xml.h \
		headers/unallocated_list.h \
		headers/unallocated_view.h main.cpp \
		src/allocated_packages.cpp \
		src/backup.cpp \
		src/box.cpp \
		src/box_view.cpp \
		src/containers.cpp \
		src/cylinder.cpp \
		src/cylinder_view.cpp \
		src/mainclient.cpp \
		src/network_client.cpp \
		src/package.cpp \
		src/post_xml.cpp \
		src/unallocated_list.cpp \
		src/unallocated_view.cpp
QMAKE_TARGET  = Cargo\ App
DESTDIR       = 
TARGET        = Cargo\ App

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/osidon/Docs/Container/container/container.pro


include /usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Cargo\ App:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: container.pro /usr/local/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllint_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		container.pro \
		/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/lib/QtConcurrent.framework/Resources/QtConcurrent.prl \
		/usr/local/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/usr/local/lib/QtXml.framework/Resources/QtXml.prl \
		/usr/local/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile container.pro
/usr/local/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.3.1_1/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/share/qt/mkspecs/qconfig.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllint_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/share/qt/mkspecs/features/qt_config.prf:
/usr/local/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/share/qt/mkspecs/features/spec_post.prf:
/usr/local/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/share/qt/mkspecs/features/toolchain.prf:
/usr/local/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/share/qt/mkspecs/features/default_pre.prf:
/usr/local/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/share/qt/mkspecs/features/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/share/qt/mkspecs/features/warn_on.prf:
/usr/local/share/qt/mkspecs/features/qt.prf:
/usr/local/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/share/qt/mkspecs/features/resources.prf:
/usr/local/share/qt/mkspecs/features/moc.prf:
/usr/local/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/share/qt/mkspecs/features/uic.prf:
/usr/local/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/share/qt/mkspecs/features/file_copies.prf:
/usr/local/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/share/qt/mkspecs/features/exceptions.prf:
/usr/local/share/qt/mkspecs/features/yacc.prf:
/usr/local/share/qt/mkspecs/features/lex.prf:
container.pro:
/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/lib/QtConcurrent.framework/Resources/QtConcurrent.prl:
/usr/local/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/usr/local/lib/QtXml.framework/Resources/QtXml.prl:
/usr/local/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile container.pro

qmake_all: FORCE


all: Makefile Cargo\ App

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents headers/allocated_packages.h headers/backup.h headers/box.h headers/box_view.h headers/containers.h headers/cylinder.h headers/cylinder_view.h headers/mainclient.h headers/network_\ client.h headers/package.h headers/post_xml.h headers/unallocated_list.h headers/unallocated_view.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/allocated_packages.cpp src/backup.cpp src/box.cpp src/box_view.cpp src/containers.cpp src/cylinder.cpp src/cylinder_view.cpp src/mainclient.cpp src/network_client.cpp src/package.cpp src/post_xml.cpp src/unallocated_list.cpp src/unallocated_view.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=12 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_box_view.cpp moc_containers.cpp moc_cylinder_view.cpp moc_mainclient.cpp moc_post_xml.cpp moc_unallocated_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_box_view.cpp moc_containers.cpp moc_cylinder_view.cpp moc_mainclient.cpp moc_post_xml.cpp moc_unallocated_view.cpp
moc_box_view.cpp: headers/box_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/osidon/Docs/Container/container/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/osidon/Docs/Container/container -I/Users/osidon/Docs/Container/container -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib headers/box_view.h -o moc_box_view.cpp

moc_containers.cpp: headers/containers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/unallocated_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		headers/unallocated_list.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		headers/allocated_packages.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		headers/box_view.h \
		headers/cylinder_view.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/osidon/Docs/Container/container/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/osidon/Docs/Container/container -I/Users/osidon/Docs/Container/container -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib headers/containers.h -o moc_containers.cpp

moc_cylinder_view.cpp: headers/cylinder_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/osidon/Docs/Container/container/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/osidon/Docs/Container/container -I/Users/osidon/Docs/Container/container -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib headers/cylinder_view.h -o moc_cylinder_view.cpp

moc_mainclient.cpp: headers/mainclient.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/lib/QtGui.framework/Headers/QIcon \
		/usr/local/lib/QtGui.framework/Headers/qicon.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/osidon/Docs/Container/container/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/osidon/Docs/Container/container -I/Users/osidon/Docs/Container/container -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib headers/mainclient.h -o moc_mainclient.cpp

moc_post_xml.cpp: headers/post_xml.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		headers/allocated_packages.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/osidon/Docs/Container/container/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/osidon/Docs/Container/container -I/Users/osidon/Docs/Container/container -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib headers/post_xml.h -o moc_post_xml.cpp

moc_unallocated_view.cpp: headers/unallocated_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/osidon/Docs/Container/container/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/osidon/Docs/Container/container -I/Users/osidon/Docs/Container/container -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtConcurrent.framework/Headers -I/usr/local/lib/QtNetwork.framework/Headers -I/usr/local/lib/QtXml.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/lib headers/unallocated_view.h -o moc_unallocated_view.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /usr/local/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/lib/QtWidgets.framework/Headers/QSplashScreen \
		/usr/local/lib/QtWidgets.framework/Headers/qsplashscreen.h \
		/usr/local/lib/QtGui.framework/Headers/QIcon \
		/usr/local/lib/QtGui.framework/Headers/qicon.h \
		headers/mainclient.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

allocated_packages.o: src/allocated_packages.cpp headers/allocated_packages.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o allocated_packages.o src/allocated_packages.cpp

backup.o: src/backup.cpp headers/backup.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonArray \
		/usr/local/lib/QtCore.framework/Headers/qjsonarray.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/lib/QtCore.framework/Headers/qjsonobject.h \
		/usr/local/lib/QtCore.framework/Headers/QChar \
		/usr/local/lib/QtCore.framework/Headers/qchar.h \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/lib/QtCore.framework/Headers/QVariantList \
		/usr/local/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/lib/QtCore.framework/Headers/QListIterator
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backup.o src/backup.cpp

box.o: src/box.cpp headers/box.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/lib/QtCore.framework/Headers/QChar \
		/usr/local/lib/QtCore.framework/Headers/qchar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o box.o src/box.cpp

box_view.o: src/box_view.cpp headers/box_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		/usr/local/lib/QtWidgets.framework/Headers/qspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o box_view.o src/box_view.cpp

containers.o: src/containers.cpp headers/containers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/unallocated_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		headers/unallocated_list.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		headers/allocated_packages.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		headers/box_view.h \
		headers/cylinder_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o containers.o src/containers.cpp

cylinder.o: src/cylinder.cpp headers/cylinder.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/lib/QtCore.framework/Headers/QChar \
		/usr/local/lib/QtCore.framework/Headers/qchar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cylinder.o src/cylinder.cpp

cylinder_view.o: src/cylinder_view.cpp headers/cylinder_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QDoubleSpinBox \
		/usr/local/lib/QtWidgets.framework/Headers/qspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cylinder_view.o src/cylinder_view.cpp

mainclient.o: src/mainclient.cpp headers/mainclient.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/lib/QtGui.framework/Headers/QIcon \
		/usr/local/lib/QtGui.framework/Headers/qicon.h \
		headers/containers.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/unallocated_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		headers/unallocated_list.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		headers/allocated_packages.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		headers/box_view.h \
		headers/cylinder_view.h \
		headers/post_xml.h \
		/usr/local/lib/QtGui.framework/Headers/QAction \
		/usr/local/lib/QtGui.framework/Headers/qaction.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/lib/QtCore.framework/Headers/QSize \
		/usr/local/lib/QtCore.framework/Headers/qsize.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/lib/QtWidgets.framework/Headers/QToolBar \
		/usr/local/lib/QtWidgets.framework/Headers/qtoolbar.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QStatusBar \
		/usr/local/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/lib/QtGui.framework/Headers/QCloseEvent \
		/usr/local/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/lib/QtWidgets.framework/Headers/QTabWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qtabwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QTabBar \
		/usr/local/lib/QtWidgets.framework/Headers/qtabbar.h \
		/usr/local/lib/QtGui.framework/Headers/QTextBlock \
		/usr/local/lib/QtGui.framework/Headers/qtextobject.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/lib/QtCore.framework/Headers/QFile \
		/usr/local/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainclient.o src/mainclient.cpp

network_client.o: src/network_client.cpp headers/network_\ client.h \
		/usr/local/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/lib/QtCore.framework/Headers/qbytearray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network_client.o src/network_client.cpp

package.o: src/package.cpp headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/lib/QtCore.framework/Headers/QChar \
		/usr/local/lib/QtCore.framework/Headers/qchar.h \
		/usr/local/lib/QtCore.framework/Headers/QDateTime \
		/usr/local/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o package.o src/package.cpp

post_xml.o: src/post_xml.cpp headers/post_xml.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		headers/allocated_packages.h \
		/usr/local/lib/QtCore.framework/Headers/QMap \
		/usr/local/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/lib/QtCore.framework/Headers/QXmlStreamWriter \
		/usr/local/lib/QtCore.framework/Headers/qxmlstream.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o post_xml.o src/post_xml.cpp

unallocated_list.o: src/unallocated_list.cpp /usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		headers/unallocated_list.h \
		headers/package.h \
		/usr/local/lib/QtCore.framework/Headers/QJsonDocument \
		/usr/local/lib/QtCore.framework/Headers/qjsondocument.h \
		headers/cylinder.h \
		/usr/local/lib/QtCore.framework/Headers/QChar \
		/usr/local/lib/QtCore.framework/Headers/qchar.h \
		headers/box.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unallocated_list.o src/unallocated_list.cpp

unallocated_view.o: src/unallocated_view.cpp headers/unallocated_view.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/lib/QtCore.framework/Headers/QString \
		/usr/local/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/lib/QtWidgets.framework/Headers/QSpinBox \
		/usr/local/lib/QtWidgets.framework/Headers/qspinbox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/QListWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qlistwidget.h \
		/usr/local/lib/QtCore.framework/Headers/QList \
		/usr/local/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/lib/QtCore.framework/Headers/QDebug \
		/usr/local/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unallocated_view.o src/unallocated_view.cpp

moc_box_view.o: moc_box_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_box_view.o moc_box_view.cpp

moc_containers.o: moc_containers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_containers.o moc_containers.cpp

moc_cylinder_view.o: moc_cylinder_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cylinder_view.o moc_cylinder_view.cpp

moc_mainclient.o: moc_mainclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainclient.o moc_mainclient.cpp

moc_post_xml.o: moc_post_xml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_post_xml.o moc_post_xml.cpp

moc_unallocated_view.o: moc_unallocated_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unallocated_view.o moc_unallocated_view.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

